# Generated by Django 3.0.8 on 2020-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default='2020-07-14'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2020-07-14'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
