# Generated by Django 3.0.8 on 2020-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('todos', '0002_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='categories.Category'),
        ),
    ]
