# Generated by Django 3.0.8 on 2020-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('todos', '0003_auto_20200708_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
