# Generated by Django 3.0.8 on 2020-07-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200708_1423'),
        ('todos', '0004_auto_20200708_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2020-07-08'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(default='general', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default='2020-07-08'),
        ),
    ]
